services:
  postgres:
    image: postgres:17
    container_name: dice_service_postgres
    restart: always
    environment:
      POSTGRES_DB: dice_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - dice_service_postgres_data:/var/lib/postgresql/data

volumes:
  dice_service_postgres_data:
